---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: default
spec:
  containers:
    -
      image: nginx
      name: nginx
      ports:
        -
          containerPort: 80
      securityContext:
        privileged: true
      volumeMounts:
        -
          mountPath: /data
          name: nfsvol
  volumes:
    -
      name: nfsvol
      persistentVolumeClaim:
        claimName: pc-nginx-1
