apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: minio01
  namespace: minio01
spec:
  clusterPair: pxlab02
  includeResources: true
  startApplications: true
  namespaces:
  - minio01
  adminClusterPair: pxlab02
  purgeDeletedResources: false
