apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pure-swagger
  name: pure-swagger
spec:
  containers:
  - image: sile16/pureswagger
    name: pure-swagger
    env:
    ports:
    - containerPort: 5000
      protocol: TCP
    resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pure-swagger
  name: pure-swagger
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: pure-swagger
  type: NodePort
status:
  loadBalancer: {}
