apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-deployment
  labels:
    app: swagger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
      - name: swagger
        image: sile16/pureswagger
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: swagger
  name: swagger
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: swagger
  type: NodePort
status:
  loadBalancer: {}
