apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume-manual
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minio"
